### ISSUE TITLE
[FIX] 낫투두 수정 뷰 텍스트뷰 영역 수정 필요

### ISSUE THREAD

**Issue by cbj0010** [DO-NOTTO-DO/AOS-NOTTODO#229]
### 🚨 오류 및 버그 사항

https://github.com/DO-NOTTO-DO/AOS-NOTTODO/assets/66460447/abfbd61e-b3c7-4cd0-b2f8-99cd9e007896
1.  글자와 체크리스트가 겹칩니다
2. 수정을 하였으나 수정이 반영되지 않습니다.

### ✅ 체크 리스트

- [ ]

**Comment by giovannijunseokim** [comment]
1번 수정해보겠습니다 !
다만 2번은 이미 같은 날짜에 낫투두가 있으므로(낫투두 또는 상황이 변경되지 않음) 수정이 반영되지 않은 것이 맞습니다 🥲

**Comment by cbj0010** [comment]
아하 기획명세 찾다가 못찾아서 일단 올렸습니다! 알려주셔서 감사티빙 😏
