### ISSUE TITLE
[FEAT] MonthlyCalendarMultiplePicker 오늘 날짜 기본값 선택

### ISSUE THREAD

**Issue by giovannijunseokim** [DO-NOTTO-DO/AOS-NOTTODO#45]
## 💡 Issue
MonthlyCalendarMultiplePicker에 오늘 날짜가 기본값으로 선택되는 기능을 추가해주시면 감사하겠습니다.

## 📝 todo
- [ ] MonthlyCalendarMultiplePicker에 오늘 날짜가 기본값으로 선택되는 기능 추가

**Comment by SSong-develop** [comment]
이거 개선했는데 아직도 동작 안하는지 확인 가능할까요?? @giovannijunseokim

**Comment by giovannijunseokim** [comment]
> 이거 개선했는데 아직도 동작 안하는지 확인 가능할까요?? @giovannijunseokim 

확인해보겠습니다 잠시만요 !

**Comment by giovannijunseokim** [comment]
아 요거 제가 코멘트를 잘못 남긴 것 같습니다 ㅠㅜㅠ
기본 날짜는 오늘로 되어있으나
"최소한 한 날짜를 선택하도록, 한 날짜가 선택된 경우 그 날짜를 재선택하여 아무 날짜도 선택되지 않은 캘린더가 나올 수 없도록"
구현해주시면 감사하겠습니다! 한번에 전달드리지 못해 죄송합니다 😥

**Comment by SSong-develop** [comment]
"최소한 한 날짜를 선택하도록, 한 날짜가 선택된 경우 그 날짜를 재 선택해 아무 날짜도 선택되지 않은 캘린더 나올 수 없도록" 이라는게.. 좀 어려운데, 일단 최소한 한 날짜를 선택해야하는건 맞죠??
